### ISSUE TITLE
Error executing more than one step in the 'Run MATLAB Command' stage

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#104]
pipeline {
    agent any
     environment { 
        PATH = "$PATH:/Applications/MATLAB_R2019a.app/bin"
    }
    stages{
        stage('checkout'){
            steps
            {
                git credentialsId: '5f59e6e8-8b32-4c30-8461-bd17c2ac4fac', url: 'https://github.com/SangaviJayagopi/matlab-plugin-bash-repo'
            }
        }
        stage('Run MATLAB Command') {
            steps
            {
                runMATLABCommand 'disp(\'hello\')'  
                runMATLABCommand 'sim('model1_oneDay')'
               // Also fails with both statements in 1 line
               //  runMATLABCommand 'disp(\'hello\');sim('model1_oneDay')'
            }
        }
        stage('Run MATLAB Tests'){
            steps
            {
                runMATLABTests()
            }
        }
        
    }                 
    
}

Console output:

Started by user Sangavi Jayagopi
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 16: Expected a symbol @ line 16, column 17.
                   runMATLABCommand 'disp(\'hello\');sim('model1_oneDay')'
                   ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:327)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Finished: FAILURE

**Comment by nbhoski** [comment]
Single quotes within single quotes is not a valid representation of a groovy unless you escape it properly or enclose it within double-quotes. you will see the highlight on the script editor as shown below.

![image](https://user-images.githubusercontent.com/47204011/84475225-cc952b80-aca9-11ea-9414-3a731dfeacbf.png)
A valid string representation would look like below.

![image](https://user-images.githubusercontent.com/47204011/84475390-1a119880-acaa-11ea-9e4c-f7b57a606887.png)
