### ISSUE TITLE
Pipeline syntax for matrix build generates error. 

### ISSUE THREAD

**Issue by SangaviJayagopi** [mathworks/jenkins-matlab-plugin#106]
pipeline{
    agent any
     environment { 
        PATH = "$PATH:/Applications/MATLAB_${VERSION}.app/bin"
    }
    stages{
        stage('checkout'){
            steps
            {
                git credentialsId: '5f59e6e8-8b32-4c30-8461-bd17c2ac4fac', url: 'https://github.com/SangaviJayagopi/matlab-plugin-bash-repo'
            }
        }
        stage('Build') {
            matrix {
                agent any
                axes {
                    axis {
                        name 'VERSION'
                        values 'R2019a', 'R2019b', 'R2020a'
                    }
                 }
            }
        }
        stage('Run MATLAB Command') {
            steps
            {
                runMATLABCommand 'disp(\'hello\')'
            }
        }
        stage('Run MATLAB Tests'){
            steps
            {
                runMATLABTests(
                                testResultsPDF:'test-results/results.pdf',
                                testResultsJUnit: 'test-results/results.xml',
                                testResultsTAP:'test-results/results.tap',
                                testResultsSimulinkTest:'test-results/results.mldatx',
                                codeCoverageCobertura: 'code-coverage/coverage.xml',
                                modelCoverageCobertura:'model-coverage/coverage.xml')
            }
        }
        
    }
}

Console Output:

Started by user Sangavi Jayagopi
Running in Durability level: MAX_SURVIVABILITY
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 14: Missing required section "stages" @ line 14, column 13.
               matrix {
               ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:561)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:522)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:327)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
Finished: FAILURE

**Comment by nbhoski** [comment]
As the log clearly mentions the error is with the syntax of matrix is used in the pipeline, and has nothing to do with plugin code as such.  if you replace the runMATLABCommand or runMATLABTests () with a simple echo step you will see the same error.

**Comment by nbhoski** [comment]
This worked for me .

`pipeline {
    agent any
    
    stages {
       
        stage('BuildAndTest') {
            matrix {
                agent any
                environment { 
        		      PATH = "${PATH}:/usr/local/MATLAB/${VERSION}/bin"
                        }
                axes {
                    axis {
                        name 'VERSION'
                        values 'R2019a', 'R2019b'
                    }
                 }
                stages {
                     stage('scm checkout') {
                         steps {
                             git credentialsId: '5f59e6e8-8b32-4c30-8461-bd17c2ac4fac', url: 'https://github.com/SangaviJayagopi/matlab-plugin-bash-repo'
                         }
                     }
            
        
                    stage('Run MATLAB commands') {
                        
                        steps {
                           
			         runMATLABCommand 'ver' 
							     
                        }
                    }
                    stage('Run MATLAB tests') {
 					    
                        steps {
							   runMATLABTests(
							                  testResultsPDF:'myresult/result.pdf'
							                  )
                        }
                    }
                }
            }
        }
    }
}
`

**Comment by SangaviJayagopi** [comment]
I knew it was not on the plugin code. 'Groovy' seems tricky!
Thanks for the correct script.
