### ISSUE TITLE
Run MATLAB Build throws a file handling error 

### ISSUE THREAD

**Issue by Vahila** [mathworks/jenkins-matlab-plugin#325]
Run MATLAB Build throws the following error.

{Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
 
Error in ciplugins.jenkins.BuildReportPlugin/runTaskGraph (line 20)
            fprintf(fID, '%s',s);
 
Error in matlab.buildtool.BuildRunner/evaluateMethodOnPlugins (line 256)
            [varargout{1:nargout}] = plugin.(methodName)(pluginData);
 
Error in matlab.buildtool.BuildRunner/run (line 222)
            runner.evaluateMethodOnPlugins("runTaskGraph", runner.PluginData.runTaskGraph);
 
Error in buildtool (line 39)
    result = runner.run(plan, taskName, taskArgs, runArgs{:});
 
Error in build_ovChyDDU (line 2)
buildtool buildApp("/AppGeneratorOutput", "SignalManager", "SignalManagerApp.mlapp", false)
}
ERROR: MATLAB error Exit Status: 0x00000001
exit status 1
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 7c7e63c5-6513-4c16-a06c-87c132804be5
com.mathworks.ci.MatlabExecutionException: Received a nonzero exit code 1 while trying to run MATLAB.
                    at com.mathworks.ci.MatlabBuildStepExecution.run(MatlabBuildStepExecution.java:64)
                    at com.mathworks.ci.MatlabBuildStepExecution.run(MatlabBuildStepExecution.java:22)
                    at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
                    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
                    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
                    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
                    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
                    at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Vahila** [comment]
The [patch fix](https://plugins.jenkins.io/matlab/releases/#version_2.13.1) will continue the build without failing for any file permission issue.

**Comment by nbhoski** [comment]
@Vahila can we close this ?

**Comment by nbhoski** [comment]
Fixed
